AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for restaurant-api definition
Parameters:
  LambdaDeployTimestamp:
    Description: Identifier of the version of the zipped lambda in s3.
    Type: Number
Resources:
  ApiGatewayRestaurantApi:
    Type: AWS::Serverless::Api
    Properties:
      AlwaysDeploy: true
      StageName: prod
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: AWS_IAM
      # MethodSettings:
      #   - HttpMethod: "*"
      #     ResourcePath: "/*"
      #     LoggingLevel: INFO
      #     DataTraceEnabled: true
      #     MetricsEnabled: true
  RestaurantApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole  # Provides write permissions to CloudWatch Logs.
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/restaurant-api-access-ssm-parameters-policy
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/restaurant-api-rds-aurora-connect-policy
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId:
              Ref: ApiGatewayRestaurantApi
      MemorySize: 256
      Timeout: 60
      Runtime: python3.14
      PackageType: Zip
      CodeUri:
        Bucket: rbif-restaurant-api
        Key: !Sub "scripts/app_${LambdaDeployTimestamp}.zip"
      Handler: main.handler